# Generated by Django 4.2.23 on 2025-09-04 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuento',
            fields=[
                ('id_cuento', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('estado_leido', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id_linea', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('contenido_lin', models.CharField(max_length=300)),
                ('cuento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='juego.cuento')),
            ],
        ),
        migrations.CreateModel(
            name='Recompensa',
            fields=[
                ('id_recompensa', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('fecha_recompensa', models.DateField()),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id_recurso', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('vidas', models.IntegerField()),
                ('monedas', models.IntegerField()),
                ('energia', models.IntegerField()),
                ('cant_alimentos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=128)),
                ('tutor_nombre', models.CharField(max_length=100)),
                ('tutor_correo', models.EmailField(max_length=254)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pictograma',
            fields=[
                ('id_pic', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('texto_original', models.CharField(max_length=300)),
                ('url_imagen', models.URLField()),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictogramas', to='juego.linea')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_nom_masc', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('img_masc', models.ImageField(upload_to='mascotas/')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mascota', to='juego.usuario')),
            ],
        ),
    ]
