# Generated by Django 4.2.23 on 2025-09-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linea',
            name='id_linea',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
